{
 "title": "Mosaic",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_os_info,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Errors",
   "type": "stat",
   "description": "Overall GPU health status (supports both AMD and Nvidia)\n- 0: normal\n- 1+: number of GPUs that are unhealthy",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(\n  # AMD GPU errors: total GPUs - healthy GPUs\n  clamp_min(\n    max_over_time(sum(gpu_nodes_total{host=~\"$host\"})[$__range:])\n    - sum(\n      gpu_health{host=~\"$host\"} \n    )\n    , 0\n  )\n) or vector(0))\n + \n(sum(\n  # Nvidia GPU errors: detect missing GPUs (expected count - actual reporting count)\n  clamp_min(\n    max_over_time(count(DCGM_FI_DEV_GPU_UTIL{host=~\"$host\"}) by (host)[$__range:])\n    - count(\n      DCGM_FI_DEV_GPU_UTIL{host=~\"$host\"}\n    ) by (host)\n    , 0\n  )\n) or vector(0))"
    }
   ]
  },
  {
   "title": "RDMA Errors",
   "type": "stat",
   "description": "Overall RDMA health status\n- 0: normal\n- 1+:  number of IB links degraded",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(\n  (\n    count((node_infiniband_physical_state_id{host=~\"$host\"} offset $__range) == 5)\n    - count(node_infiniband_physical_state_id{host=~\"$host\"} == 5)\n  ), 0\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Outliers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GPU Throughput Outliers",
   "type": "stat",
   "description": "Number of GPU pairs that have throughput over 3 stddev\n- 0: normal\n- 1+: number of GPU pair with sub-optimal transfer time",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((mosaic_gpu_pair_bw{source_hostname=~\"$host\"}-scalar(avg(mosaic_gpu_pair_bw)))/scalar(stddev(mosaic_gpu_pair_bw))>3) OR vector(0)",
     "legendFormat": "{{source_hostname}}/{{source_pci_bus_id}}->{{dest_hostname}}/{{dest_pci_bus_id}}"
    }
   ]
  },
  {
   "title": "GPU Latency Outliers",
   "type": "stat",
   "description": "Number of GPU pairs that have latency over 3 stddev\n- 0: normal\n- 1+: number of GPU pair with severely degraded transfer time",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((mosaic_gpu_pair_latency{source_hostname=~\"$host\"}-scalar(avg(mosaic_gpu_pair_latency)))/scalar(stddev(mosaic_gpu_pair_latency))>3) OR vector(0)",
     "legendFormat": "{{source_hostname}}/{{source_pci_bus_id}}->{{dest_hostname}}/{{dest_pci_bus_id}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Workload Processes",
   "type": "stat",
   "description": "Indicates if GPU CCL processes are running\n- 0: there is no workload, or collective communication processes have crashed\n- 1+: normal",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_num_threads{host=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Active Profiler Metrics",
   "type": "stat",
   "description": "Number of active metrics collected by NCCL profiler plugin\n- 0: nothing is collected, indicating possible issues\n- \\>0: metrics are being collected",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"^(nccl_).*\"}) OR vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}