{
 "title": "InfiniBand (Node Exporter)",
 "description": "Detailed InfiniBand metrics from node_exporter.",
 "tags": [ "InfiniBand" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(node_infiniband_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Xmit Data Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$instance\"}[$__interval])) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Recv Data Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_infiniband_port_data_received_bytes_total{instance=~\"$instance\"}[$__interval])) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Xmit Packet Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_infiniband_port_packets_transmitted_total{instance=~\"$instance\"}[$__interval])) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Recv Packet Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(node_infiniband_port_packets_received_total{instance=~\"$instance\"}[$__interval])) * 8",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Max HCA Line Data Rate",
   "type": "table",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "max by (instance) (\n  sum by (instance) (\n    node_infiniband_rate_bytes_per_second{instance=~\"$instance\"} * 8 \n    * (node_infiniband_physical_state_id{instance=~\"$instance\"} == bool 5)\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Xmit Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$instance\"}[$__interval])) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Recv Data Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_infiniband_port_data_received_bytes_total{instance=~\"$instance\"}[$__interval])) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Link Errors",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(instance) (irate(node_infiniband_symbol_error_total{instance=~\"$instance\"}[$__interval])) + \nsum by(instance) (irate(node_infiniband_port_errors_received_total{instance=~\"$instance\"}[$__interval])) +\nsum by(instance) (irate(node_infiniband_port_constraint_errors_received_total{instance=~\"$instance\"}[$__interval])) +\nsum by(instance) (irate(node_infiniband_port_constraint_errors_transmitted_total{instance=~\"$instance\"}[$__interval])) +\nsum by(instance) (irate(node_infiniband_local_link_integrity_errors_total{instance=~\"$instance\"}[$__interval])) +\nsum by(instance) (irate(node_infiniband_excessive_buffer_overrun_errors_total{instance=~\"$instance\"}[$__interval])) +\nsum by(instance) (irate(node_infiniband_port_receive_switch_relay_errors_total{instance=~\"$instance\"}[$__interval])) +\nsum by(instance) (irate(node_infiniband_port_receive_remote_physical_errors_total{instance=~\"$instance\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Downed Links",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "max by (instance, device) (\n    (count by (instance, device) (node_infiniband_physical_state_id{instance=~\"$instance\"} == 2) > bool 0)\n        or \n    (count by (instance, device) (node_infiniband_physical_state_id{instance=~\"$instance\"} == 6) > bool 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disconnected Links",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "max by (instance, device) (\n    (count by (instance, device) (node_infiniband_physical_state_id{instance=~\"$instance\"} == 3) > bool 0)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${instance}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "repeat": "instance",
   "collapsed": true,
   "panels": [
    {
     "title": "Xmit Data Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$instance\"}[$__interval])) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Recv Data Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_data_received_bytes_total{instance=~\"$instance\"}[$__interval])) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Max HCA Line Data Rate",
     "type": "table",
     "gridPos": { "h": 10, "w": 16, "x": 8, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "max by (device, port, hca_type, firmware_version) (\n  node_infiniband_rate_bytes_per_second{instance=~\"$instance\"} * 8\n  * (node_infiniband_physical_state_id{instance=~\"$instance\"} == bool 5)\n  * on(region, instance, device) group_left(hca_type, firmware_version)\n  node_infiniband_info\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Xmit Packet Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_packets_transmitted_total{instance=~\"$instance\"}[$__interval])) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Recv Packet Rate",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(node_infiniband_port_packets_received_total{instance=~\"$instance\"}[$__interval])) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Xmit Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_infiniband_port_data_transmitted_bytes_total{instance=~\"$instance\"}[$__interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Recv Data Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "irate(node_infiniband_port_data_received_bytes_total{instance=~\"$instance\"}[$__interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Xmit Packet Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_infiniband_port_packets_transmitted_total{instance=~\"$instance\"}[$__interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Recv Packet Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(node_infiniband_port_packets_received_total{instance=~\"$instance\"}[$__interval]) * 8",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Link Status",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
     "targets": [
      {
       "expr": "sum by (device) (\n    node_infiniband_physical_state_id{instance=~\"$instance\"}\n)",
       "legendFormat": "{{label_name}}"
      }
     ]
    },
    {
     "title": "Link Errors",
     "type": "status-history",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 71 },
     "targets": [
      {
       "expr": "sum by(device) (irate(node_infiniband_symbol_error_total{instance=~\"$instance\"}[$__interval])) + \nsum by(device) (irate(node_infiniband_port_errors_received_total{instance=~\"$instance\"}[$__interval])) +\nsum by(device) (irate(node_infiniband_port_constraint_errors_received_total{instance=~\"$instance\"}[$__interval])) +\nsum by(device) (irate(node_infiniband_port_constraint_errors_transmitted_total{instance=~\"$instance\"}[$__interval])) +\nsum by(device) (irate(node_infiniband_local_link_integrity_errors_total{instance=~\"$instance\"}[$__interval])) +\nsum by(device) (irate(node_infiniband_excessive_buffer_overrun_errors_total{instance=~\"$instance\"}[$__interval])) +\nsum by(device) (irate(node_infiniband_port_receive_switch_relay_errors_total{instance=~\"$instance\"}[$__interval])) +\nsum by(device) (irate(node_infiniband_port_receive_remote_physical_errors_total{instance=~\"$instance\"}[$__interval]))",
       "legendFormat": "{{label_name}}"
      }
     ]
    }
   ]
  }
 ]
}