{
 "title": "System Details - AMD",
 "description": "GPU and node details for systems with AMD GPUs. This dashboard utilizes metrics from node exporter, AMD device exporter, and process exporter.",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(node_os_info,host)"
    }
   },
   {
    "name": "pcie_port",
    "label": "PCIe Port",
    "query": {
     "query": "label_values(gpu_pcie_port{host=~\"$host\"},pcie_port)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Host Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Use % by Host",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "avg((100 - (sum(rate(node_cpu_seconds_total{host=~\"$host\", mode=\"idle\"}[2m])) by (cpu, host) / sum(rate(node_cpu_seconds_total{host=~\"$host\"}[2m])) by (cpu, host)) * 100)) by (host)",
       "legendFormat": "{{host}}"
      }
     ]
    },
    {
     "title": "Active RDMA Ports by Host",
     "type": "timeseries",
     "description": "Count of RDMA ports in a connected state by host.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "count(node_infiniband_physical_state_id{host=~\"$host\"} == 5) by (host) ",
       "legendFormat": "{{host}}"
      }
     ]
    }
   ]
  },
  { "title": "GPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "GPU Power Use",
   "type": "timeseries",
   "description": "Power use per GPU as measured by rocm-smi tools.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "(gpu_average_package_power{host=~\"$host\"} or gpu_package_power{host=~\"$host\"}) * on(host, gpu_id) group_left(pcie_port) gpu_pcie_port{host=~\"$host\", pcie_port=~\"$pcie_port\"}",
     "legendFormat": "{{host}}/{{pcie_port}}"
    }
   ]
  },
  {
   "title": "GPU % Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "expr": "(gpu_gfx_activity{host=~\"$host\"}) * on(host, gpu_id) group_left(pcie_port) gpu_pcie_port{host=~\"$host\", pcie_port=~\"$pcie_port\"}",
     "legendFormat": "{{host}}/{{pcie_port}}"
    }
   ]
  },
  {
   "title": "GPU Edge Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "(gpu_edge_temperature{host=~\"$host\"}) * on(host, gpu_id) group_left(pcie_port) gpu_pcie_port{host=~\"$host\", pcie_port=~\"$pcie_port\"}",
     "legendFormat": "{{host}}/{{pcie_port}}"
    }
   ]
  },
  {
   "title": "GPU Memory Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(gpu_memory_temperature{host=~\"$host\"}) * on(host, gpu_id) group_left(pcie_port) gpu_pcie_port{host=~\"$host\", pcie_port=~\"$pcie_port\"}",
     "legendFormat": "{{host}}/{{pcie_port}}"
    }
   ]
  },
  {
   "title": "GPU Memory Engine Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(gpu_umc_activity{host=~\"$host\"}) * on(host, gpu_id) group_left(pcie_port) gpu_pcie_port{host=~\"$host\", pcie_port=~\"$pcie_port\"}",
     "legendFormat": "{{host}}/{{pcie_port}}"
    }
   ]
  },
  { "title": "ROCm/RCCL Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "ROCm/RCCL Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(namedprocess_namegroup_thread_count{groupname=\"rccl-tests\"} or namedprocess_namegroup_thread_count{groupname=\"ray\"}) by (host)",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}